### ISSUE TITLE
Drag & Drop section

### ISSUE THREAD

**Issue by mark-summerfield** [fltk-rs/fltk-book#6]
It would be helpful in the drag & drop section if you specified:
- which widgets support drag & drop of filenames out-of-the-box (e.g., Input)
- which widgets' `handle` method can receive `DndRelease` (or `Paste`) events.

For example, I'd like to make a frame able to accept a filename drop, but this doesn't seem possible.

**Comment by MoAlyousef** [comment]
It should be possible:

```rust
use fltk::{app, frame::Frame, enums::*, prelude::*, window::Window};

fn main() {
    let app = app::App::default();
    let mut wind = Window::default().with_size(400, 300);
    let mut frame = Frame::default().with_size(200, 100).center_of(&wind);
    frame.set_frame(FrameType::DownBox);
    wind.end();
    wind.show();

    // Handle drag and drop
    frame.handle({
        let mut dnd = false;
        let mut released = false;
        move |f, ev| match ev {
            Event::DndEnter => {
                dnd = true;
                true
            }
            Event::DndDrag => true,
            Event::DndRelease => {
                released = true;
                true
            }
            Event::Paste => {
                if dnd && released {
                    let path = app::event_text();
                    let path = path.trim();
                    let path = path.replace("file://", "");
                    f.set_label(&path);
                    dnd = false;
                    released = false;
                    true
                } else {
                    false
                }
            }
            Event::DndLeave => {
                dnd = false;
                released = false;
                true
            }
            _ => false,
        }
    });

    app.run().unwrap();
}
```

I'll try to update the info regarding what widgets support out of the box.

**Comment by mark-summerfield** [comment]
I tried that, then I tried just println!("{event:?}"}); and it turned out that it gets DndEnter and DndLeave but _not_ DndDrag, DndRelease, or Paste.

**Comment by MoAlyousef** [comment]
It might be a platform issue. What platform did you try this on?
On Windows 11 it seems to work correctly.
Also `println!("{event}");` might be more accurate since the debug output actually prints the bitfield representation (of the bitfield crate, something like `Push | Released | Enter | Leave | Drag | Focus | Unfocus | Show | Paste | SelectionClear | MouseWheel | DndEnter | DndDrag | DndLeave | DndRelease`). Whereas the display output is the actual event.

**Comment by mark-summerfield** [comment]
OK, I must have made a mistake when I tested it. I just tried your code above and it worked first time. Sorry! (Thinking back I think I might have done the handle() call on the Scroll instead of the Frame.)

PS I am testing on Linux Debian 11 and Windows 7 and Windows 10.
